package SCT.Tela;

import SCT.DAO.ChamadosRecentesDAO;
import SCT.DAO.PadraoDAO;
import SCT.Utilidade.ConnectionManager;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ródney
 */
public class TelaCoordenador extends javax.swing.JFrame {

    public TelaCoordenador() {
                initComponents();
                this.setSize(new Dimension(600, 400));
                this.setResizable(false);
                this.setLocationRelativeTo(null);
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMBPrincipal = new javax.swing.JMenuBar();
        jMCadastro = new javax.swing.JMenu();
        jMICadastraTecnico = new javax.swing.JMenuItem();
        jMICadastraMaquina = new javax.swing.JMenuItem();
        jMICadastraFerramenta = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMICadastrarChamado = new javax.swing.JMenuItem();
        jMICadastrarFerramentaChamado = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMIConsultaChamadosRecentesDeCadaTecnico = new javax.swing.JMenuItem();
        jMAjuda = new javax.swing.JMenu();
        jMISobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle de técnicos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMCadastro.setText("Cadastrar");

        jMICadastraTecnico.setText("Tecnico");
        jMICadastraTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastraTecnicoActionPerformed(evt);
            }
        });
        jMCadastro.add(jMICadastraTecnico);

        jMICadastraMaquina.setText("Maquina");
        jMICadastraMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastraMaquinaActionPerformed(evt);
            }
        });
        jMCadastro.add(jMICadastraMaquina);

        jMICadastraFerramenta.setText("Ferramenta");
        jMICadastraFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastraFerramentaActionPerformed(evt);
            }
        });
        jMCadastro.add(jMICadastraFerramenta);

        jMBPrincipal.add(jMCadastro);

        jMenu1.setText("Lançamento");

        jMICadastrarChamado.setText("Chamado");
        jMICadastrarChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastrarChamadoActionPerformed(evt);
            }
        });
        jMenu1.add(jMICadastrarChamado);

        jMICadastrarFerramentaChamado.setText("Ferramenta e chamado");
        jMICadastrarFerramentaChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastrarFerramentaChamadoActionPerformed(evt);
            }
        });
        jMenu1.add(jMICadastrarFerramentaChamado);

        jMBPrincipal.add(jMenu1);

        jMenu2.setText("Consulta");

        jMIConsultaChamadosRecentesDeCadaTecnico.setText("Chamados recentes de cada técnico");
        jMIConsultaChamadosRecentesDeCadaTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConsultaChamadosRecentesDeCadaTecnicoActionPerformed(evt);
            }
        });
        jMenu2.add(jMIConsultaChamadosRecentesDeCadaTecnico);

        jMBPrincipal.add(jMenu2);

        jMAjuda.setText("Ajuda");

        jMISobre.setText("Sobre");
        jMISobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISobreActionPerformed(evt);
            }
        });
        jMAjuda.add(jMISobre);

        jMBPrincipal.add(jMAjuda);

        setJMenuBar(jMBPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        finaliza();
    }//GEN-LAST:event_formWindowClosing

    private void jMICadastraTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastraTecnicoActionPerformed
        // TODO add your handling code here:
        new TelaGestaoTecnico(this, true).setVisible(true);
    }//GEN-LAST:event_jMICadastraTecnicoActionPerformed

    private void jMICadastraMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastraMaquinaActionPerformed
        // TODO add your handling code here:
        new TelaGestaoMaquina(this, true).setVisible(true);
    }//GEN-LAST:event_jMICadastraMaquinaActionPerformed

    private void jMICadastraFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastraFerramentaActionPerformed
        // TODO add your handling code here:
        new TelaGestaoFerramenta(this, true).setVisible(true);
    }//GEN-LAST:event_jMICadastraFerramentaActionPerformed

    private void jMICadastrarChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastrarChamadoActionPerformed
        // TODO add your handling code here:
        new TelaGestaoChamado(this, true).setVisible(true);
    }//GEN-LAST:event_jMICadastrarChamadoActionPerformed

    private void jMICadastrarFerramentaChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastrarFerramentaChamadoActionPerformed
        // TODO add your handling code here:
        new TelaGestaoFerramentaChamado(this, true).setVisible(true);
    }//GEN-LAST:event_jMICadastrarFerramentaChamadoActionPerformed

    private void jMIConsultaChamadosRecentesDeCadaTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConsultaChamadosRecentesDeCadaTecnicoActionPerformed
        try {
            // TODO add your handling code here:
            PadraoDAO dadosDAO = new ChamadosRecentesDAO();
            TelaPesquisaChamadosRecentes listagem = new TelaPesquisaChamadosRecentes(
                this,
                true,
                "Chamados Mais Recentes",
                dadosDAO,
                "chamados_recentes");
        listagem.setLocationRelativeTo(this);
        listagem.setSize(new Dimension(1000,500));
        listagem.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCoordenador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jMIConsultaChamadosRecentesDeCadaTecnicoActionPerformed

    private void jMISobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISobreActionPerformed
        // TODO add your handling code here:
        UUID userId = UUID.randomUUID();
        System.out.println(String.valueOf(userId).substring(0, 7));
    }//GEN-LAST:event_jMISobreActionPerformed

    private void finaliza() {
        ConnectionManager.desconecta();
        System.exit(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMAjuda;
    private javax.swing.JMenuBar jMBPrincipal;
    private javax.swing.JMenu jMCadastro;
    private javax.swing.JMenuItem jMICadastraFerramenta;
    private javax.swing.JMenuItem jMICadastraMaquina;
    private javax.swing.JMenuItem jMICadastraTecnico;
    private javax.swing.JMenuItem jMICadastrarChamado;
    private javax.swing.JMenuItem jMICadastrarFerramentaChamado;
    private javax.swing.JMenuItem jMIConsultaChamadosRecentesDeCadaTecnico;
    private javax.swing.JMenuItem jMISobre;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    // End of variables declaration//GEN-END:variables
}
