/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SCT.Tela;

import SCT.DAO.ChamadoDAO;
import SCT.DAO.FerramentaChamadoDAO;
import SCT.DAO.FerramentaDAO;
import SCT.DAO.MaquinaDAO;
import SCT.DAO.PadraoDAO;
import SCT.DAO.TecnicoDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ródney
 */
public class TelaPesquisas extends javax.swing.JDialog {

    /**
     * Creates new form TelaPesquisas
     */
    PadraoDAO dadosDAO;
    public TelaPesquisas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPOpcoes = new javax.swing.JPanel();
        jBConsultarFerramentas = new javax.swing.JButton();
        jBConsultarMaquinas = new javax.swing.JButton();
        jBConsultarChamados = new javax.swing.JButton();
        jBConsultarTecnicos = new javax.swing.JButton();
        jBConsultarFerramentasChamados = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPOpcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultar"));

        jBConsultarFerramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Ferramenta.png"))); // NOI18N
        jBConsultarFerramentas.setText(" Ferramentas");
        jBConsultarFerramentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarFerramentasActionPerformed(evt);
            }
        });

        jBConsultarMaquinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Maquina.png"))); // NOI18N
        jBConsultarMaquinas.setText("Máquinas");
        jBConsultarMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarMaquinasActionPerformed(evt);
            }
        });

        jBConsultarChamados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Chamado.png"))); // NOI18N
        jBConsultarChamados.setText("Chamados");
        jBConsultarChamados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarChamadosActionPerformed(evt);
            }
        });

        jBConsultarTecnicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Tecnico.png"))); // NOI18N
        jBConsultarTecnicos.setText("Técnicos");
        jBConsultarTecnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarTecnicosActionPerformed(evt);
            }
        });

        jBConsultarFerramentasChamados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/FerramentaChamado.png"))); // NOI18N
        jBConsultarFerramentasChamados.setText("Ferramentas Chamado");
        jBConsultarFerramentasChamados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarFerramentasChamadosActionPerformed(evt);
            }
        });

        jBSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Sair.png"))); // NOI18N
        jBSair.setText("Fechar");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPOpcoesLayout = new javax.swing.GroupLayout(jPOpcoes);
        jPOpcoes.setLayout(jPOpcoesLayout);
        jPOpcoesLayout.setHorizontalGroup(
            jPOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBConsultarTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBConsultarFerramentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBConsultarChamados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(38, 38, 38)
                .addGroup(jPOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBConsultarFerramentasChamados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBConsultarMaquinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPOpcoesLayout.setVerticalGroup(
            jPOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOpcoesLayout.createSequentialGroup()
                .addGroup(jPOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBConsultarTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBConsultarFerramentasChamados, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBConsultarFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBConsultarMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBConsultarChamados, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        jMenu2.setText("Ajuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBConsultarTecnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarTecnicosActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            dadosDAO = new TecnicoDAO();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPesquisas.class.getName()).log(Level.SEVERE, null, ex);
        }
        TelaPesquisa listagem = new TelaPesquisa(
                null,
                true,
                "Técnicos Armazenados",
                dadosDAO,
                "tecnico");
        listagem.setLocationRelativeTo(this);
        listagem.setVisible(true);
    }//GEN-LAST:event_jBConsultarTecnicosActionPerformed

    private void jBConsultarFerramentasChamadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarFerramentasChamadosActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            dadosDAO = new FerramentaChamadoDAO();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPesquisas.class.getName()).log(Level.SEVERE, null, ex);
        }
        TelaPesquisa listagem = new TelaPesquisa(
                null,
                true,
                "Ferramentas e Chamados Armazenados",
                dadosDAO,
                "ferramenta_chamado");
        listagem.setLocationRelativeTo(null);
        listagem.setVisible(true);
    }//GEN-LAST:event_jBConsultarFerramentasChamadosActionPerformed

    private void jBConsultarFerramentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarFerramentasActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            dadosDAO = new FerramentaDAO();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPesquisas.class.getName()).log(Level.SEVERE, null, ex);
        }
        TelaPesquisa listagem = new TelaPesquisa(
                null,
                true,
                "Ferramentas Armazenadas",
                dadosDAO,
                "ferramenta");
        listagem.setLocationRelativeTo(null);
        listagem.setVisible(true);
    }//GEN-LAST:event_jBConsultarFerramentasActionPerformed

    private void jBConsultarMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarMaquinasActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            dadosDAO = new MaquinaDAO();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPesquisas.class.getName()).log(Level.SEVERE, null, ex);
        }
        TelaPesquisa listagem = new TelaPesquisa(
                null,
                true,
                "Máquinas Armazenadas",
                dadosDAO,
                "maquina");
        listagem.setLocationRelativeTo(null);
        listagem.setVisible(true);
    }//GEN-LAST:event_jBConsultarMaquinasActionPerformed

    private void jBConsultarChamadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarChamadosActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            dadosDAO = new ChamadoDAO();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPesquisas.class.getName()).log(Level.SEVERE, null, ex);
        }
        TelaPesquisa listagem = new TelaPesquisa(
                null,
                true,
                "Chamados Armazenados",
                dadosDAO,
                "chamado");
        listagem.setLocationRelativeTo(null);
        listagem.setVisible(true);
    }//GEN-LAST:event_jBConsultarChamadosActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBSairActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultarChamados;
    private javax.swing.JButton jBConsultarFerramentas;
    private javax.swing.JButton jBConsultarFerramentasChamados;
    private javax.swing.JButton jBConsultarMaquinas;
    private javax.swing.JButton jBConsultarTecnicos;
    private javax.swing.JButton jBSair;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPOpcoes;
    // End of variables declaration//GEN-END:variables
}
